*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:19:23 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
writing pidfile to uwsgi.pid
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xb8f540
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xb8f540 pid: 4654 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4654)
spawned uWSGI worker 1 (pid: 4658, cores: 1)
spawned uWSGI worker 2 (pid: 4659, cores: 1)
spawned uWSGI worker 3 (pid: 4660, cores: 1)
spawned uWSGI worker 4 (pid: 4661, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 4659|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 882 bytes} [Sun Mar  8 09:19:39 2020] GET / => generated 9205 bytes in 1963 msecs (HTTP/1.1 401) 7 headers in 368 bytes (1 switches on core 0)
[pid: 4658|app: 0|req: 1/2] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 09:20:01 2020] GET / => generated 11512 bytes in 1947 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4661|app: 0|req: 1/3] 127.0.0.1 () {48 vars in 909 bytes} [Sun Mar  8 09:20:03 2020] GET /favicon.ico => generated 13172 bytes in 304 msecs (HTTP/1.1 404) 4 headers in 117 bytes (1 switches on core 0)
[pid: 4661|app: 0|req: 2/4] 127.0.0.1 () {50 vars in 986 bytes} [Sun Mar  8 09:21:46 2020] GET /category/ => generated 14413 bytes in 596 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4661|app: 0|req: 3/5] 127.0.0.1 () {50 vars in 1028 bytes} [Sun Mar  8 09:21:59 2020] GET /category/?limit=1&offset=1 => generated 14543 bytes in 176 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4660|app: 0|req: 1/6] 127.0.0.1 () {58 vars in 1227 bytes} [Sun Mar  8 09:22:05 2020] POST /category/?limit=1&offset=1 => generated 13653 bytes in 741 msecs (HTTP/1.1 400) 7 headers in 369 bytes (1 switches on core 0)
[pid: 4660|app: 0|req: 2/7] 127.0.0.1 () {50 vars in 994 bytes} [Sun Mar  8 09:22:37 2020] GET / => generated 11512 bytes in 162 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4661|app: 0|req: 4/8] 127.0.0.1 () {50 vars in 989 bytes} [Sun Mar  8 09:22:49 2020] GET /?format=api => generated 11864 bytes in 160 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4660|app: 0|req: 3/9] 127.0.0.1 () {50 vars in 1018 bytes} [Sun Mar  8 09:22:52 2020] GET /category/?format=api => generated 14561 bytes in 178 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4659|app: 0|req: 2/10] 127.0.0.1 () {50 vars in 1009 bytes} [Sun Mar  8 09:22:57 2020] GET /?format=api => generated 11864 bytes in 388 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4661|app: 0|req: 5/11] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 09:23:10 2020] GET / => generated 11512 bytes in 151 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Sun Mar  8 09:28:04 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4658)...
Gracefully killing worker 3 (pid: 4660)...
Gracefully killing worker 2 (pid: 4659)...
Gracefully killing worker 4 (pid: 4661)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:28:05 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2639f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2639f40 pid: 4654 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4654)
spawned uWSGI worker 1 (pid: 4869, cores: 1)
spawned uWSGI worker 2 (pid: 4870, cores: 1)
spawned uWSGI worker 3 (pid: 4871, cores: 1)
spawned uWSGI worker 4 (pid: 4872, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 09:28:08 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 4870)...
Gracefully killing worker 1 (pid: 4869)...
Gracefully killing worker 3 (pid: 4871)...
Gracefully killing worker 4 (pid: 4872)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:28:09 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1b7ef40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1b7ef40 pid: 4654 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4654)
spawned uWSGI worker 1 (pid: 4877, cores: 1)
spawned uWSGI worker 2 (pid: 4878, cores: 1)
spawned uWSGI worker 3 (pid: 4879, cores: 1)
spawned uWSGI worker 4 (pid: 4880, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 09:30:55 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4877)...
Gracefully killing worker 2 (pid: 4878)...
Gracefully killing worker 3 (pid: 4879)...
Gracefully killing worker 4 (pid: 4880)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:30:56 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1127f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1127f40 pid: 4654 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4654)
spawned uWSGI worker 1 (pid: 4929, cores: 1)
spawned uWSGI worker 2 (pid: 4930, cores: 1)
spawned uWSGI worker 3 (pid: 4931, cores: 1)
spawned uWSGI worker 4 (pid: 4932, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 4932|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:31:10 2020] GET / => generated 11512 bytes in 736 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4932|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:31:16 2020] GET / => generated 11512 bytes in 155 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 4929)...
Gracefully killing worker 2 (pid: 4930)...
Gracefully killing worker 4 (pid: 4932)...
Gracefully killing worker 3 (pid: 4931)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:31:38 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x188ef40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x188ef40 pid: 4654 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4654)
spawned uWSGI worker 1 (pid: 4983, cores: 1)
spawned uWSGI worker 2 (pid: 4984, cores: 1)
spawned uWSGI worker 3 (pid: 4985, cores: 1)
spawned uWSGI worker 4 (pid: 4986, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 4986|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:31:45 2020] GET / => generated 11512 bytes in 746 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4986|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 989 bytes} [Sun Mar  8 09:31:57 2020] GET /?format=api => generated 11864 bytes in 157 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 4985|app: 0|req: 1/3] 127.0.0.1 () {50 vars in 1018 bytes} [Sun Mar  8 09:32:00 2020] GET /category/?format=api => generated 14561 bytes in 735 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4986|app: 0|req: 3/4] 127.0.0.1 () {52 vars in 1049 bytes} [Sun Mar  8 09:36:35 2020] GET /category/?format=api => generated 14561 bytes in 236 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4986|app: 0|req: 4/5] 127.0.0.1 () {52 vars in 1049 bytes} [Sun Mar  8 09:36:41 2020] GET /category/?format=api => generated 14561 bytes in 180 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 4986|app: 0|req: 5/6] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 09:36:53 2020] GET / => generated 11512 bytes in 152 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:40:45 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
writing pidfile to uwsgi.pid
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xbd8540
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0xbd8540 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 5365, cores: 1)
spawned uWSGI worker 2 (pid: 5366, cores: 1)
spawned uWSGI worker 3 (pid: 5367, cores: 1)
spawned uWSGI worker 4 (pid: 5368, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 5367|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:40:59 2020] GET / => generated 11512 bytes in 2715 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5367|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:41:06 2020] GET / => generated 11512 bytes in 526 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5368|app: 0|req: 1/3] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 09:41:43 2020] GET / => generated 11512 bytes in 2470 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5367|app: 0|req: 3/4] 127.0.0.1 () {50 vars in 996 bytes} [Sun Mar  8 09:41:53 2020] GET /categoryitems/ => generated 11689 bytes in 591 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5366|app: 0|req: 1/5] 127.0.0.1 () {50 vars in 1043 bytes} [Sun Mar  8 09:41:59 2020] GET /categoryitems/?limit=1&offset=1 => generated 12088 bytes in 2604 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5367|app: 0|req: 4/6] 127.0.0.1 () {52 vars in 1074 bytes} [Sun Mar  8 09:42:54 2020] GET /categoryitems/?limit=1&offset=1 => generated 12088 bytes in 167 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5367|app: 0|req: 5/7] 127.0.0.1 () {52 vars in 1074 bytes} [Sun Mar  8 09:42:56 2020] GET /categoryitems/?limit=1&offset=1 => generated 12088 bytes in 171 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 5365)...
Gracefully killing worker 3 (pid: 5367)...
Gracefully killing worker 4 (pid: 5368)...
Gracefully killing worker 2 (pid: 5366)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:43:04 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1f2df40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1f2df40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 5435, cores: 1)
spawned uWSGI worker 2 (pid: 5436, cores: 1)
spawned uWSGI worker 3 (pid: 5437, cores: 1)
spawned uWSGI worker 4 (pid: 5438, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 5438|app: 0|req: 1/1] 127.0.0.1 () {52 vars in 1074 bytes} [Sun Mar  8 09:43:14 2020] GET /categoryitems/?limit=1&offset=1 => generated 12088 bytes in 2566 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5435|app: 0|req: 1/2] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 09:43:18 2020] GET / => generated 11512 bytes in 2661 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 2/3] 127.0.0.1 () {50 vars in 986 bytes} [Sun Mar  8 09:43:24 2020] GET /category/ => generated 14413 bytes in 581 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 3/4] 127.0.0.1 () {50 vars in 1028 bytes} [Sun Mar  8 09:43:29 2020] GET /category/?limit=1&offset=1 => generated 14543 bytes in 575 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 4/5] 127.0.0.1 () {50 vars in 1045 bytes} [Sun Mar  8 09:43:45 2020] GET /category/?limit=1&offset=1 => generated 14543 bytes in 559 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 5/6] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 09:44:40 2020] GET / => generated 11512 bytes in 500 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 6/7] 127.0.0.1 () {46 vars in 883 bytes} [Sun Mar  8 09:45:06 2020] GET / => generated 9205 bytes in 67 msecs (HTTP/1.1 401) 7 headers in 368 bytes (1 switches on core 0)
[pid: 5437|app: 0|req: 1/8] 127.0.0.1 () {48 vars in 931 bytes} [Sun Mar  8 09:45:16 2020] GET / => generated 11512 bytes in 736 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 5438|app: 0|req: 7/9] 127.0.0.1 () {46 vars in 858 bytes} [Sun Mar  8 09:45:17 2020] GET /favicon.ico => generated 13172 bytes in 20 msecs (HTTP/1.1 404) 4 headers in 117 bytes (1 switches on core 0)
[pid: 5437|app: 0|req: 2/10] 127.0.0.1 () {50 vars in 987 bytes} [Sun Mar  8 09:45:25 2020] GET /category/ => generated 14413 bytes in 184 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 5438|app: 0|req: 8/11] 127.0.0.1 () {48 vars in 931 bytes} [Sun Mar  8 09:53:57 2020] GET / => generated 11512 bytes in 156 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Sun Mar  8 09:57:10 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 5435)...
Gracefully killing worker 3 (pid: 5437)...
Gracefully killing worker 4 (pid: 5438)...
Gracefully killing worker 2 (pid: 5436)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:57:11 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x17cef40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x17cef40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6478, cores: 1)
spawned uWSGI worker 2 (pid: 6479, cores: 1)
spawned uWSGI worker 3 (pid: 6480, cores: 1)
spawned uWSGI worker 4 (pid: 6481, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 09:57:14 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6478)...
Gracefully killing worker 2 (pid: 6479)...
Gracefully killing worker 3 (pid: 6480)...
Gracefully killing worker 4 (pid: 6481)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:57:15 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1532f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1532f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6490, cores: 1)
spawned uWSGI worker 2 (pid: 6491, cores: 1)
spawned uWSGI worker 3 (pid: 6492, cores: 1)
spawned uWSGI worker 4 (pid: 6493, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 09:57:19 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6491)...
Gracefully killing worker 1 (pid: 6490)...
Gracefully killing worker 3 (pid: 6492)...
Gracefully killing worker 4 (pid: 6493)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 09:57:20 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ffaf40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1ffaf40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6497, cores: 1)
spawned uWSGI worker 2 (pid: 6498, cores: 1)
spawned uWSGI worker 3 (pid: 6499, cores: 1)
spawned uWSGI worker 4 (pid: 6500, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 10:00:09 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6498)...
Gracefully killing worker 1 (pid: 6497)...
Gracefully killing worker 3 (pid: 6499)...
Gracefully killing worker 4 (pid: 6500)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:00:10 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x243af40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x243af40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6588, cores: 1)
spawned uWSGI worker 2 (pid: 6589, cores: 1)
spawned uWSGI worker 3 (pid: 6590, cores: 1)
spawned uWSGI worker 4 (pid: 6591, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 10:00:12 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6589)...
Gracefully killing worker 1 (pid: 6588)...
Gracefully killing worker 3 (pid: 6590)...
Gracefully killing worker 4 (pid: 6591)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:00:14 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1847f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1847f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6597, cores: 1)
spawned uWSGI worker 2 (pid: 6598, cores: 1)
spawned uWSGI worker 3 (pid: 6600, cores: 1)
spawned uWSGI worker 4 (pid: 6601, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6597)...
Gracefully killing worker 3 (pid: 6600)...
Gracefully killing worker 2 (pid: 6598)...
Gracefully killing worker 4 (pid: 6601)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:01:05 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1523f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x1523f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6629, cores: 1)
spawned uWSGI worker 2 (pid: 6630, cores: 1)
spawned uWSGI worker 3 (pid: 6631, cores: 1)
spawned uWSGI worker 4 (pid: 6632, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6632|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 961 bytes} [Sun Mar  8 10:01:24 2020] GET / => generated 11512 bytes in 2365 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6632|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 986 bytes} [Sun Mar  8 10:01:48 2020] GET /category/ => generated 14413 bytes in 179 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
Sun Mar  8 10:02:10 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6629)...
Gracefully killing worker 2 (pid: 6630)...
Gracefully killing worker 3 (pid: 6631)...
Gracefully killing worker 4 (pid: 6632)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:02:11 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1fb8f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1fb8f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6691, cores: 1)
spawned uWSGI worker 2 (pid: 6692, cores: 1)
spawned uWSGI worker 3 (pid: 6693, cores: 1)
spawned uWSGI worker 4 (pid: 6694, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 10:02:17 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6692)...
Gracefully killing worker 1 (pid: 6691)...
Gracefully killing worker 3 (pid: 6693)...
Gracefully killing worker 4 (pid: 6694)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:02:18 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1de2f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1de2f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6698, cores: 1)
spawned uWSGI worker 2 (pid: 6699, cores: 1)
spawned uWSGI worker 3 (pid: 6700, cores: 1)
spawned uWSGI worker 4 (pid: 6701, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Sun Mar  8 10:07:59 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6698)...
Gracefully killing worker 4 (pid: 6701)...
Gracefully killing worker 2 (pid: 6699)...
Gracefully killing worker 3 (pid: 6700)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Sun Mar  8 10:08:00 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xde5f40
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0xde5f40 pid: 5360 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 5360)
spawned uWSGI worker 1 (pid: 6805, cores: 1)
spawned uWSGI worker 2 (pid: 6806, cores: 1)
spawned uWSGI worker 3 (pid: 6807, cores: 1)
spawned uWSGI worker 4 (pid: 6808, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6808|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 986 bytes} [Sun Mar  8 10:08:04 2020] GET /category/ => generated 14413 bytes in 730 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 978 bytes} [Sun Mar  8 10:20:57 2020] GET /user/ => generated 13364 bytes in 55 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 3/3] 127.0.0.1 () {48 vars in 938 bytes} [Sun Mar  8 10:21:08 2020] GET /docs => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 4/4] 127.0.0.1 () {48 vars in 940 bytes} [Sun Mar  8 10:21:08 2020] GET /docs/ => generated 409645 bytes in 1077 msecs (HTTP/1.1 200) 5 headers in 161 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 5/5] 127.0.0.1 () {48 vars in 884 bytes} [Sun Mar  8 10:21:09 2020] GET /docs/schema.js => generated 29648 bytes in 205 msecs (HTTP/1.1 200) 5 headers in 165 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 1/6] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 10:36:44 2020] GET / => generated 11512 bytes in 722 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 2/7] 127.0.0.1 () {50 vars in 976 bytes} [Sun Mar  8 10:36:47 2020] GET /tag/ => generated 14052 bytes in 239 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 6/8] 127.0.0.1 () {58 vars in 1234 bytes} [Sun Mar  8 10:37:02 2020] POST /tag/ => generated 13698 bytes in 181 msecs (HTTP/1.1 400) 7 headers in 369 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 7/9] 127.0.0.1 () {50 vars in 974 bytes} [Sun Mar  8 10:38:08 2020] GET /ad/ => generated 16045 bytes in 664 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
Not Found: /media/uploads/0_5bxvnlz.jpg
[pid: 6806|app: 0|req: 1/10] 127.0.0.1 () {50 vars in 1025 bytes} [Sun Mar  8 10:38:26 2020] GET /media/uploads/0_5bxvnlz.jpg => generated 13220 bytes in 1011 msecs (HTTP/1.1 404) 4 headers in 117 bytes (1 switches on core 0)
[pid: 6806|app: 0|req: 2/11] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 10:42:15 2020] GET / => generated 11512 bytes in 1534 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6805|app: 0|req: 1/12] 127.0.0.1 () {50 vars in 992 bytes} [Sun Mar  8 10:42:40 2020] GET /articleList/ => generated 22406 bytes in 3351 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 8/13] 127.0.0.1 () {50 vars in 992 bytes} [Sun Mar  8 10:42:42 2020] GET /articleList/ => generated 22406 bytes in 983 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 3/14] 127.0.0.1 () {50 vars in 1139 bytes} [Sun Mar  8 10:43:39 2020] GET /articleList/?author=&status=&publish_date=&is_active=true&item=&categorys=&tags= => generated 23839 bytes in 927 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 9/15] 127.0.0.1 () {50 vars in 1225 bytes} [Sun Mar  8 10:43:58 2020] GET /articleList/?author=&categorys=&is_active=true&item=&offset=1&publish_date=&status=&tags= => generated 22503 bytes in 894 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 10/16] 127.0.0.1 () {48 vars in 940 bytes} [Sun Mar  8 10:47:05 2020] GET /admin => generated 0 bytes in 3 msecs (HTTP/1.1 301) 4 headers in 126 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 11/17] 127.0.0.1 () {48 vars in 942 bytes} [Sun Mar  8 10:47:05 2020] GET /admin/ => generated 0 bytes in 76 msecs (HTTP/1.1 302) 7 headers in 273 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 12/18] 127.0.0.1 () {48 vars in 979 bytes} [Sun Mar  8 10:47:05 2020] GET /admin/login/?next=/admin/ => generated 1857 bytes in 280 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 4/19] 127.0.0.1 () {58 vars in 1226 bytes} [Sun Mar  8 10:47:16 2020] POST /admin/login/?next=/admin/ => generated 0 bytes in 731 msecs (HTTP/1.1 302) 10 headers in 571 bytes (1 switches on core 0)
[pid: 6806|app: 0|req: 3/20] 127.0.0.1 () {52 vars in 1080 bytes} [Sun Mar  8 10:47:17 2020] GET /admin/ => generated 5873 bytes in 387 msecs (HTTP/1.1 200) 6 headers in 235 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 13/21] 127.0.0.1 () {50 vars in 1056 bytes} [Sun Mar  8 10:47:23 2020] GET /admin/article/item/ => generated 7070 bytes in 301 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 5/22] 127.0.0.1 () {48 vars in 940 bytes} [Sun Mar  8 10:47:24 2020] GET /admin/jsi18n/ => generated 7678 bytes in 69 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 6/23] 127.0.0.1 () {50 vars in 1087 bytes} [Sun Mar  8 10:47:27 2020] GET /admin/article/item/1/change/ => generated 7302 bytes in 613 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6806|app: 0|req: 4/24] 127.0.0.1 () {48 vars in 949 bytes} [Sun Mar  8 10:47:27 2020] GET /admin/jsi18n/ => generated 7678 bytes in 61 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 14/25] 127.0.0.1 () {50 vars in 1056 bytes} [Sun Mar  8 10:47:48 2020] GET /admin/article/item/ => generated 7070 bytes in 329 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6805|app: 0|req: 2/26] 127.0.0.1 () {50 vars in 1087 bytes} [Sun Mar  8 10:47:51 2020] GET /admin/article/item/9/change/ => generated 7308 bytes in 460 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 15/27] 127.0.0.1 () {48 vars in 949 bytes} [Sun Mar  8 10:47:51 2020] GET /admin/jsi18n/ => generated 7678 bytes in 74 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 7/28] 127.0.0.1 () {50 vars in 1056 bytes} [Sun Mar  8 10:47:58 2020] GET /admin/article/item/ => generated 7070 bytes in 286 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 16/29] 127.0.0.1 () {50 vars in 1043 bytes} [Sun Mar  8 10:48:09 2020] GET /admin/ => generated 5873 bytes in 113 msecs (HTTP/1.1 200) 6 headers in 235 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 17/30] 127.0.0.1 () {50 vars in 1062 bytes} [Sun Mar  8 10:48:12 2020] GET /admin/article/article/ => generated 10281 bytes in 339 msecs (HTTP/1.1 200) 7 headers in 390 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 8/31] 127.0.0.1 () {48 vars in 943 bytes} [Sun Mar  8 10:48:13 2020] GET /admin/jsi18n/ => generated 7678 bytes in 49 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 9/32] 127.0.0.1 () {50 vars in 1043 bytes} [Sun Mar  8 10:48:16 2020] GET /admin/ => generated 5873 bytes in 142 msecs (HTTP/1.1 200) 6 headers in 235 bytes (1 switches on core 0)
Internal Server Error: /admin/article/tag/
Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/options.py", line 566, in get_field
    return self.fields_map[field_name]
KeyError: 'article_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/utils.py", line 276, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/utils.py", line 307, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/options.py", line 568, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: Tag has no field named 'article_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py", line 326, in result_list
    'results': list(results(cl))}
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py", line 302, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py", line 293, in __init__
    super().__init__(*items)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/templatetags/admin_list.py", line 212, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/contrib/admin/utils.py", line 285, in lookup_field
    value = attr(obj)
  File "./article/admin.py", line 26, in article_count
    return Article.objects.filter(tag=obj).count()
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1153, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1015, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1379, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'tag' into field. Choices are: articles, author, author_id, content, expiration_date, fav_num, id, is_active, item, item_id, pic, praise_num, publish_date, read_num, slug, status, tags, title
[pid: 6808|app: 0|req: 18/33] 127.0.0.1 () {50 vars in 1054 bytes} [Sun Mar  8 10:48:19 2020] GET /admin/article/tag/ => generated 347670 bytes in 1129 msecs (HTTP/1.1 500) 5 headers in 292 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 10/34] 127.0.0.1 () {50 vars in 1043 bytes} [Sun Mar  8 10:48:23 2020] GET /admin/ => generated 5873 bytes in 134 msecs (HTTP/1.1 200) 6 headers in 235 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 19/35] 127.0.0.1 () {50 vars in 1064 bytes} [Sun Mar  8 10:48:26 2020] GET /admin/article/category/ => generated 5314 bytes in 220 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 20/36] 127.0.0.1 () {48 vars in 944 bytes} [Sun Mar  8 10:48:26 2020] GET /admin/jsi18n/ => generated 7678 bytes in 39 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 21/37] 127.0.0.1 () {50 vars in 1043 bytes} [Sun Mar  8 10:48:29 2020] GET /admin/ => generated 5873 bytes in 143 msecs (HTTP/1.1 200) 6 headers in 235 bytes (1 switches on core 0)
[pid: 6807|app: 0|req: 11/38] 127.0.0.1 () {48 vars in 930 bytes} [Sun Mar  8 10:54:20 2020] GET / => generated 11512 bytes in 616 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 22/39] 127.0.0.1 () {50 vars in 992 bytes} [Sun Mar  8 10:54:25 2020] GET /articleList/ => generated 22406 bytes in 872 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 23/40] 127.0.0.1 () {50 vars in 1073 bytes} [Sun Mar  8 10:56:26 2020] GET /articleList/?search=%E6%A0%B9%E8%8C%8E%E7%B1%BB => generated 14789 bytes in 241 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 24/41] 127.0.0.1 () {50 vars in 1132 bytes} [Sun Mar  8 10:56:37 2020] GET /articleList/?ordering=id&search=%E6%A0%B9%E8%8C%8E%E7%B1%BB => generated 14991 bytes in 230 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6808|app: 0|req: 25/42] 127.0.0.1 () {50 vars in 1073 bytes} [Sun Mar  8 10:57:36 2020] GET /articleList/?search=%E6%9C%BA%E5%99%A8%E4%BA%BA => generated 21747 bytes in 917 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:34:41 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
writing pidfile to uwsgi.pid
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x20075b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x20075b0 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6186, cores: 1)
spawned uWSGI worker 2 (pid: 6187, cores: 1)
spawned uWSGI worker 3 (pid: 6188, cores: 1)
spawned uWSGI worker 4 (pid: 6189, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6188|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 926 bytes} [Mon Mar  9 11:35:42 2020] GET / => generated 9205 bytes in 367 msecs (HTTP/1.1 401) 7 headers in 368 bytes (1 switches on core 0)
[pid: 6186|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 926 bytes} [Mon Mar  9 11:35:43 2020] GET / => generated 9205 bytes in 394 msecs (HTTP/1.1 401) 7 headers in 368 bytes (1 switches on core 0)
[pid: 6187|app: 0|req: 1/3] 127.0.0.1 () {48 vars in 974 bytes} [Mon Mar  9 11:35:45 2020] GET / => generated 11512 bytes in 712 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6188|app: 0|req: 2/4] 127.0.0.1 () {48 vars in 953 bytes} [Mon Mar  9 11:35:46 2020] GET /favicon.ico => generated 13173 bytes in 16 msecs (HTTP/1.1 404) 4 headers in 117 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 1/5] 127.0.0.1 () {50 vars in 1040 bytes} [Mon Mar  9 11:35:49 2020] GET /categoryitems/ => generated 11689 bytes in 726 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 2/6] 192.168.0.188 () {44 vars in 797 bytes} [Mon Mar  9 11:37:27 2020] GET / => generated 9205 bytes in 29 msecs (HTTP/1.1 401) 7 headers in 368 bytes (1 switches on core 0)
[pid: 6187|app: 0|req: 2/7] 192.168.0.188 () {48 vars in 934 bytes} [Mon Mar  9 11:37:41 2020] GET / => generated 11624 bytes in 165 msecs (HTTP/1.1 200) 6 headers in 322 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 6188|app: 0|req: 3/8] 192.168.0.188 () {48 vars in 917 bytes} [Mon Mar  9 11:37:41 2020] GET /favicon.ico => generated 13177 bytes in 20 msecs (HTTP/1.1 404) 4 headers in 117 bytes (1 switches on core 0)
[pid: 6188|app: 0|req: 4/9] 192.168.0.188 () {50 vars in 994 bytes} [Mon Mar  9 11:37:48 2020] GET /category/ => generated 14433 bytes in 376 msecs (HTTP/1.1 200) 6 headers in 328 bytes (1 switches on core 0)
[pid: 6187|app: 0|req: 3/10] 192.168.0.188 () {48 vars in 946 bytes} [Mon Mar  9 11:38:02 2020] GET /xadmin => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 127 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 3/11] 192.168.0.188 () {48 vars in 948 bytes} [Mon Mar  9 11:38:02 2020] GET /xadmin/ => generated 4163 bytes in 78 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6188|app: 0|req: 5/12] 192.168.0.188 () {48 vars in 894 bytes} [Mon Mar  9 11:38:02 2020] GET /xadmin/jsi18n/ => generated 4170 bytes in 74 msecs (HTTP/1.1 200) 7 headers in 389 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 4/13] 192.168.0.188 () {58 vars in 1185 bytes} [Mon Mar  9 11:38:13 2020] POST /xadmin/ => generated 0 bytes in 323 msecs (HTTP/1.1 302) 10 headers in 572 bytes (1 switches on core 0)
[pid: 6186|app: 0|req: 2/14] 192.168.0.188 () {52 vars in 1072 bytes} [Mon Mar  9 11:38:13 2020] GET /xadmin/ => generated 11620 bytes in 125 msecs (HTTP/1.1 200) 6 headers in 236 bytes (1 switches on core 0)
[pid: 6187|app: 0|req: 4/15] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:38:14 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 26 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 5/16] 192.168.0.188 () {50 vars in 1075 bytes} [Mon Mar  9 11:38:24 2020] GET /xadmin/article/item/add/ => generated 17368 bytes in 136 msecs (HTTP/1.1 200) 7 headers in 390 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 6/17] 192.168.0.188 () {48 vars in 955 bytes} [Mon Mar  9 11:38:24 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6188|app: 0|req: 6/18] 192.168.0.188 () {50 vars in 1084 bytes} [Mon Mar  9 11:38:29 2020] GET /xadmin/article/item/ => generated 34961 bytes in 182 msecs (HTTP/1.1 200) 8 headers in 521 bytes (1 switches on core 0)
[pid: 6188|app: 0|req: 7/19] 192.168.0.188 () {48 vars in 951 bytes} [Mon Mar  9 11:38:29 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 24 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 7/20] 192.168.0.188 () {48 vars in 986 bytes} [Mon Mar  9 11:38:42 2020] GET /docs => generated 0 bytes in 1 msecs (HTTP/1.1 301) 4 headers in 125 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 8/21] 192.168.0.188 () {48 vars in 988 bytes} [Mon Mar  9 11:38:42 2020] GET /docs/ => generated 410029 bytes in 951 msecs (HTTP/1.1 200) 5 headers in 161 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 9/22] 192.168.0.188 () {48 vars in 936 bytes} [Mon Mar  9 11:38:43 2020] GET /docs/schema.js => generated 29652 bytes in 203 msecs (HTTP/1.1 200) 5 headers in 165 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 10/23] 192.168.0.188 () {48 vars in 992 bytes} [Mon Mar  9 11:38:56 2020] GET /xadmin/ => generated 11620 bytes in 52 msecs (HTTP/1.1 200) 6 headers in 236 bytes (1 switches on core 0)
[pid: 6189|app: 0|req: 11/24] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:38:57 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 15 msecs (HTTP/1.1 200) 4 headers in 123 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 3 (pid: 6188)...
Gracefully killing worker 1 (pid: 6186)...
Gracefully killing worker 2 (pid: 6187)...
Gracefully killing worker 4 (pid: 6189)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:46:20 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1cc0f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1cc0f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6570, cores: 1)
spawned uWSGI worker 2 (pid: 6571, cores: 1)
spawned uWSGI worker 3 (pid: 6572, cores: 1)
spawned uWSGI worker 4 (pid: 6573, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/hadoop0/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./newsapi/urls.py", line 48, in <module>
    path('xadmin/', xadmin.site.urls),
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 340, in urls
    return self.get_urls(), self.name, self.app_name
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 293, in get_urls
    from xadmin.views.base import BaseAdminView
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/__init__.py", line 3, in <module>
    from .base import BaseAdminPlugin, BaseAdminView, CommAdminView, ModelAdminView, filter_hook, csrf_protect_m, BaseAdminObject
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/base.py", line 33, in <module>
    from xadmin.models import Log
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/models.py", line 46, in <module>
    class Bookmark(models.Model):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class xadmin.models.Bookmark doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[pid: 6571|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:46:42 2020] GET /xadmin/ => generated 169250 bytes in 568 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /xadmin/
Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/hadoop0/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./newsapi/urls.py", line 48, in <module>
    path('xadmin/', xadmin.site.urls),
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 340, in urls
    return self.get_urls(), self.name, self.app_name
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 293, in get_urls
    from xadmin.views.base import BaseAdminView
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/__init__.py", line 3, in <module>
    from .base import BaseAdminPlugin, BaseAdminView, CommAdminView, ModelAdminView, filter_hook, csrf_protect_m, BaseAdminObject
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/base.py", line 33, in <module>
    from xadmin.models import Log
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/models.py", line 46, in <module>
    class Bookmark(models.Model):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class xadmin.models.Bookmark doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[pid: 6572|app: 0|req: 1/2] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:47:11 2020] GET /xadmin/ => generated 169250 bytes in 473 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/hadoop0/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./newsapi/urls.py", line 48, in <module>
    path('xadmin/', xadmin.site.urls),
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 340, in urls
    return self.get_urls(), self.name, self.app_name
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/sites.py", line 293, in get_urls
    from xadmin.views.base import BaseAdminView
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/__init__.py", line 3, in <module>
    from .base import BaseAdminPlugin, BaseAdminView, CommAdminView, ModelAdminView, filter_hook, csrf_protect_m, BaseAdminObject
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/views/base.py", line 33, in <module>
    from xadmin.models import Log
  File "/home/hadoop0/Django_P/Django_API/newsapi/extra_apps/xadmin/models.py", line 46, in <module>
    class Bookmark(models.Model):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/db/models/base.py", line 108, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class xadmin.models.Bookmark doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[pid: 6572|app: 0|req: 2/3] 192.168.0.188 () {48 vars in 978 bytes} [Mon Mar  9 11:47:29 2020] GET / => generated 169024 bytes in 142 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6570)...
Gracefully killing worker 2 (pid: 6571)...
Gracefully killing worker 3 (pid: 6572)...
Gracefully killing worker 4 (pid: 6573)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:51:41 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x11b9f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x11b9f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6689, cores: 1)
spawned uWSGI worker 2 (pid: 6690, cores: 1)
spawned uWSGI worker 3 (pid: 6691, cores: 1)
spawned uWSGI worker 4 (pid: 6692, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6692|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1009 bytes} [Mon Mar  9 11:51:51 2020] GET / => generated 11624 bytes in 727 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 6691|app: 0|req: 1/2] 192.168.0.188 () {48 vars in 992 bytes} [Mon Mar  9 11:52:03 2020] GET /xadmin/ => generated 11620 bytes in 494 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6691|app: 0|req: 2/3] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:52:04 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6689)...
Gracefully killing worker 2 (pid: 6690)...
Gracefully killing worker 4 (pid: 6692)...
Gracefully killing worker 3 (pid: 6691)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:54:19 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1fa7f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x1fa7f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6773, cores: 1)
spawned uWSGI worker 2 (pid: 6774, cores: 1)
spawned uWSGI worker 3 (pid: 6775, cores: 1)
spawned uWSGI worker 4 (pid: 6776, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6775|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:54:28 2020] GET /xadmin/ => generated 11620 bytes in 511 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 1/2] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:54:29 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 356 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6775|app: 0|req: 2/3] 192.168.0.188 () {48 vars in 978 bytes} [Mon Mar  9 11:54:35 2020] GET / => generated 11624 bytes in 348 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 6775|app: 0|req: 3/4] 192.168.0.188 () {50 vars in 1038 bytes} [Mon Mar  9 11:54:38 2020] GET /category/ => generated 14433 bytes in 195 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
[pid: 6775|app: 0|req: 4/5] 192.168.0.188 () {50 vars in 1068 bytes} [Mon Mar  9 11:54:44 2020] GET /categoryPrimaryKeyitems/ => generated 10381 bytes in 163 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 2/6] 192.168.0.188 () {52 vars in 1099 bytes} [Mon Mar  9 11:55:21 2020] GET /categoryPrimaryKeyitems/ => generated 10381 bytes in 417 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 3/7] 192.168.0.188 () {48 vars in 992 bytes} [Mon Mar  9 11:55:27 2020] GET /xadmin/ => generated 11620 bytes in 100 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 4/8] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:55:27 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 9 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6774|app: 0|req: 1/9] 192.168.0.188 () {48 vars in 992 bytes} [Mon Mar  9 11:55:27 2020] GET /xadmin/ => generated 11620 bytes in 484 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 5/10] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:55:41 2020] GET /xadmin/ => generated 11620 bytes in 58 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6775|app: 0|req: 5/11] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:55:41 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6774|app: 0|req: 2/12] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:56:37 2020] GET /xadmin/ => generated 11620 bytes in 53 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6774|app: 0|req: 3/13] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:56:37 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 27 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 6/14] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:56:40 2020] GET /xadmin/ => generated 11620 bytes in 54 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6776|app: 0|req: 7/15] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:56:40 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 16 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
Mon Mar  9 11:57:00 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6774)...
Gracefully killing worker 1 (pid: 6773)...
Gracefully killing worker 3 (pid: 6775)...
Gracefully killing worker 4 (pid: 6776)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:57:01 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc8af90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xc8af90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6891, cores: 1)
spawned uWSGI worker 2 (pid: 6892, cores: 1)
spawned uWSGI worker 3 (pid: 6893, cores: 1)
spawned uWSGI worker 4 (pid: 6894, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6892|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:57:04 2020] GET /xadmin/ => generated 11621 bytes in 513 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6894|app: 0|req: 1/2] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:57:05 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 361 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
Mon Mar  9 11:57:17 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6892)...
Gracefully killing worker 3 (pid: 6893)...
Gracefully killing worker 1 (pid: 6891)...
Gracefully killing worker 4 (pid: 6894)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:57:18 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xa74f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xa74f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6916, cores: 1)
spawned uWSGI worker 2 (pid: 6917, cores: 1)
spawned uWSGI worker 3 (pid: 6918, cores: 1)
spawned uWSGI worker 4 (pid: 6919, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Mon Mar  9 11:57:52 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 6916)...
Gracefully killing worker 3 (pid: 6918)...
Gracefully killing worker 2 (pid: 6917)...
Gracefully killing worker 4 (pid: 6919)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:57:53 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf87f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xf87f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6934, cores: 1)
spawned uWSGI worker 2 (pid: 6935, cores: 1)
spawned uWSGI worker 3 (pid: 6936, cores: 1)
spawned uWSGI worker 4 (pid: 6937, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Mon Mar  9 11:58:41 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6935)...
Gracefully killing worker 1 (pid: 6934)...
Gracefully killing worker 3 (pid: 6936)...
Gracefully killing worker 4 (pid: 6937)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 11:58:42 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xa5df90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xa5df90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 6964, cores: 1)
spawned uWSGI worker 2 (pid: 6965, cores: 1)
spawned uWSGI worker 3 (pid: 6966, cores: 1)
spawned uWSGI worker 4 (pid: 6967, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 6965|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1023 bytes} [Mon Mar  9 11:59:17 2020] GET /xadmin/ => generated 11621 bytes in 506 msecs (HTTP/1.1 200) 6 headers in 228 bytes (1 switches on core 0)
[pid: 6965|app: 0|req: 2/2] 192.168.0.188 () {48 vars in 938 bytes} [Mon Mar  9 11:59:18 2020] GET /xadmin/jsi18n/ => generated 7678 bytes in 29 msecs (HTTP/1.1 200) 4 headers in 115 bytes (1 switches on core 0)
[pid: 6967|app: 0|req: 1/3] 192.168.0.188 () {48 vars in 988 bytes} [Mon Mar  9 11:59:22 2020] GET /docs/ => generated 410029 bytes in 1488 msecs (HTTP/1.1 200) 5 headers in 153 bytes (1 switches on core 0)
[pid: 6967|app: 0|req: 2/4] 192.168.0.188 () {48 vars in 936 bytes} [Mon Mar  9 11:59:23 2020] GET /docs/schema.js => generated 29652 bytes in 193 msecs (HTTP/1.1 200) 4 headers in 151 bytes (1 switches on core 0)
Mon Mar  9 12:00:48 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 2 (pid: 6965)...
Gracefully killing worker 1 (pid: 6964)...
Gracefully killing worker 3 (pid: 6966)...
Gracefully killing worker 4 (pid: 6967)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 12:00:49 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x108cf90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x108cf90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 7013, cores: 1)
spawned uWSGI worker 2 (pid: 7014, cores: 1)
spawned uWSGI worker 3 (pid: 7015, cores: 1)
spawned uWSGI worker 4 (pid: 7016, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Mon Mar  9 14:31:55 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 7013)...
Gracefully killing worker 2 (pid: 7014)...
Gracefully killing worker 3 (pid: 7015)...
Gracefully killing worker 4 (pid: 7016)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 14:31:56 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1e1cf90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x1e1cf90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 8080, cores: 1)
spawned uWSGI worker 2 (pid: 8081, cores: 1)
spawned uWSGI worker 3 (pid: 8082, cores: 1)
spawned uWSGI worker 4 (pid: 8083, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Mon Mar  9 15:26:36 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 3 (pid: 8082)...
Gracefully killing worker 1 (pid: 8080)...
Gracefully killing worker 2 (pid: 8081)...
Gracefully killing worker 4 (pid: 8083)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 15:26:37 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xaebf90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xaebf90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 9002, cores: 1)
spawned uWSGI worker 2 (pid: 9003, cores: 1)
spawned uWSGI worker 3 (pid: 9004, cores: 1)
spawned uWSGI worker 4 (pid: 9005, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 9005|app: 0|req: 1/1] 192.168.0.188 () {50 vars in 1019 bytes} [Mon Mar  9 15:27:09 2020] GET /docs/ => generated 410029 bytes in 1603 msecs (HTTP/1.1 200) 5 headers in 153 bytes (1 switches on core 0)
[pid: 9002|app: 0|req: 1/2] 192.168.0.188 () {48 vars in 936 bytes} [Mon Mar  9 15:27:11 2020] GET /docs/schema.js => generated 29652 bytes in 546 msecs (HTTP/1.1 200) 4 headers in 151 bytes (1 switches on core 0)
[pid: 9004|app: 0|req: 1/3] 192.168.0.188 () {48 vars in 978 bytes} [Mon Mar  9 15:29:36 2020] GET / => generated 11870 bytes in 738 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 9004|app: 0|req: 2/4] 192.168.0.188 () {50 vars in 1038 bytes} [Mon Mar  9 15:29:41 2020] GET /category/ => generated 14679 bytes in 190 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
...brutally killing workers...
Gracefully killing worker 4 (pid: 9005)...
Gracefully killing worker 3 (pid: 9004)...
Gracefully killing worker 2 (pid: 9003)...
Gracefully killing worker 1 (pid: 9002)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 17:39:54 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x2659f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x2659f90 pid: 6179 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 6179)
spawned uWSGI worker 1 (pid: 12207, cores: 1)
spawned uWSGI worker 2 (pid: 12208, cores: 1)
spawned uWSGI worker 3 (pid: 12209, cores: 1)
spawned uWSGI worker 4 (pid: 12210, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 19:22:39 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
writing pidfile to uwsgi.pid
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x148c5b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 17 seconds on interpreter 0x148c5b0 pid: 3887 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3887)
spawned uWSGI worker 1 (pid: 3902, cores: 1)
spawned uWSGI worker 2 (pid: 3903, cores: 1)
spawned uWSGI worker 3 (pid: 3904, cores: 1)
spawned uWSGI worker 4 (pid: 3905, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 3905|app: 0|req: 1/1] 127.0.0.1 () {48 vars in 957 bytes} [Mon Mar  9 19:23:15 2020] GET / => generated 9451 bytes in 1785 msecs (HTTP/1.1 401) 7 headers in 360 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 1005 bytes} [Mon Mar  9 19:23:18 2020] GET / => generated 11758 bytes in 593 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 3904|app: 0|req: 1/3] 127.0.0.1 () {52 vars in 1006 bytes} [Mon Mar  9 19:23:20 2020] GET /favicon.ico => generated 13173 bytes in 361 msecs (HTTP/1.1 404) 3 headers in 103 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 3/4] 127.0.0.1 () {50 vars in 1048 bytes} [Mon Mar  9 19:23:24 2020] GET /categorySlugitems/ => generated 10639 bytes in 268 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 4/5] 127.0.0.1 () {50 vars in 1036 bytes} [Mon Mar  9 19:23:29 2020] GET /articleList/ => generated 22691 bytes in 1144 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
Internal Server Error: /articleList/
Traceback (most recent call last):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 494, in resolve
    for pattern in self.url_patterns:
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/hadoop0/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./newsapi/urls.py", line 21, in <module>
    import article.views as view
  File "/home/hadoop0/Django_P/Django_API/newsapi/article/views.py", line 13, in <module>
    from .myfilter import ArticleFilter
  File "/home/hadoop0/Django_P/Django_API/newsapi/article/myfilter.py", line 9, in <module>
    class ArticleFilter(django_filters.rest_framework.FilterSet):
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django_filters/filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/hadoop0/anaconda3/lib/python3.5/site-packages/django_filters/filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: categorys
[pid: 3902|app: 0|req: 1/6] 127.0.0.1 () {52 vars in 1067 bytes} [Mon Mar  9 19:25:27 2020] GET /articleList/ => generated 147103 bytes in 523 msecs (HTTP/1.1 500) 4 headers in 130 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 5/7] 127.0.0.1 () {52 vars in 1067 bytes} [Mon Mar  9 19:25:53 2020] GET /articleList/ => generated 22691 bytes in 282 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 2/8] 127.0.0.1 () {52 vars in 1067 bytes} [Mon Mar  9 19:26:26 2020] GET /articleList/ => generated 22691 bytes in 677 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 3/9] 127.0.0.1 () {50 vars in 1063 bytes} [Mon Mar  9 19:26:43 2020] GET /articleList/?search= => generated 22855 bytes in 271 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 6/10] 127.0.0.1 () {50 vars in 1143 bytes} [Mon Mar  9 19:27:30 2020] GET /articleList/?search=%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD => generated 23235 bytes in 313 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3904|app: 0|req: 2/11] 127.0.0.1 () {48 vars in 996 bytes} [Mon Mar  9 19:44:17 2020] GET /articleList => generated 0 bytes in 2 msecs (HTTP/1.1 301) 3 headers in 118 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 4/12] 127.0.0.1 () {48 vars in 998 bytes} [Mon Mar  9 19:44:17 2020] GET /articleList/ => generated 22691 bytes in 252 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3903|app: 0|req: 1/13] 127.0.0.1 () {50 vars in 1081 bytes} [Mon Mar  9 19:44:28 2020] GET /articleList/?limit=1&offset=1 => generated 21195 bytes in 856 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 7/14] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:44:31 2020] GET /articleList/?limit=1&offset=2 => generated 18249 bytes in 272 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 5/15] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:44:36 2020] GET /articleList/?limit=1&offset=1 => generated 21195 bytes in 269 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3903|app: 0|req: 2/16] 127.0.0.1 () {50 vars in 1080 bytes} [Mon Mar  9 19:44:39 2020] GET /articleList/?limit=1 => generated 22819 bytes in 271 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 6/17] 127.0.0.1 () {50 vars in 1089 bytes} [Mon Mar  9 19:44:41 2020] GET /articleList/?limit=1&offset=1 => generated 21195 bytes in 270 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 8/18] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:44:43 2020] GET /articleList/?limit=1&offset=2 => generated 18249 bytes in 265 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 9/19] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:44:50 2020] GET /articleList/?limit=1&offset=1 => generated 21195 bytes in 266 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 10/20] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:44:54 2020] GET /articleList/?limit=1&offset=2 => generated 18249 bytes in 257 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 11/21] 127.0.0.1 () {50 vars in 1080 bytes} [Mon Mar  9 19:44:58 2020] GET /articleList/?limit=1 => generated 22819 bytes in 270 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 12/22] 127.0.0.1 () {50 vars in 1089 bytes} [Mon Mar  9 19:45:02 2020] GET /articleList/?limit=1&offset=1 => generated 21195 bytes in 262 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3904|app: 0|req: 3/23] 127.0.0.1 () {50 vars in 1098 bytes} [Mon Mar  9 19:45:04 2020] GET /articleList/?limit=1&offset=2 => generated 18249 bytes in 521 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 13/24] 127.0.0.1 () {50 vars in 1080 bytes} [Mon Mar  9 19:50:20 2020] GET /articleList/?limit=1 => generated 22819 bytes in 269 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 14/25] 127.0.0.1 () {48 vars in 998 bytes} [Mon Mar  9 22:18:31 2020] GET /articleList/ => generated 22691 bytes in 346 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 15/26] 127.0.0.1 () {48 vars in 984 bytes} [Mon Mar  9 22:19:11 2020] GET /docs/ => generated 409891 bytes in 1269 msecs (HTTP/1.1 200) 5 headers in 153 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 16/27] 127.0.0.1 () {48 vars in 928 bytes} [Mon Mar  9 22:19:13 2020] GET /docs/schema.js => generated 29648 bytes in 221 msecs (HTTP/1.1 200) 4 headers in 151 bytes (1 switches on core 0)
[pid: 3905|app: 0|req: 17/28] 127.0.0.1 () {48 vars in 910 bytes} [Mon Mar  9 22:21:16 2020] GET /item/ => generated 628 bytes in 147 msecs (HTTP/1.1 200) 5 headers in 148 bytes (1 switches on core 0)
[pid: 3904|app: 0|req: 4/29] 127.0.0.1 () {48 vars in 932 bytes} [Mon Mar  9 22:21:34 2020] GET /hot_articleList/ => generated 8888 bytes in 191 msecs (HTTP/1.1 200) 5 headers in 143 bytes (1 switches on core 0)
[pid: 3904|app: 0|req: 5/30] 127.0.0.1 () {48 vars in 932 bytes} [Mon Mar  9 22:21:37 2020] GET /hot_articleList/ => generated 8888 bytes in 187 msecs (HTTP/1.1 200) 5 headers in 143 bytes (1 switches on core 0)
[pid: 3902|app: 0|req: 7/31] 127.0.0.1 () {48 vars in 932 bytes} [Mon Mar  9 22:21:38 2020] GET /hot_articleList/ => generated 8888 bytes in 185 msecs (HTTP/1.1 200) 5 headers in 143 bytes (1 switches on core 0)
...brutally killing workers...
Gracefully killing worker 2 (pid: 3903)...
Gracefully killing worker 1 (pid: 3902)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Mar  9 23:01:24 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1ffff90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x1ffff90 pid: 3887 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 3887)
spawned uWSGI worker 1 (pid: 6411, cores: 1)
spawned uWSGI worker 2 (pid: 6412, cores: 1)
spawned uWSGI worker 3 (pid: 6413, cores: 1)
spawned uWSGI worker 4 (pid: 6414, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 14:26:02 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
writing pidfile to uwsgi.pid
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xc295b0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 6 seconds on interpreter 0xc295b0 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 12731, cores: 1)
spawned uWSGI worker 2 (pid: 12732, cores: 1)
spawned uWSGI worker 3 (pid: 12733, cores: 1)
spawned uWSGI worker 4 (pid: 12734, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 12733|app: 0|req: 1/1] 127.0.0.1 () {46 vars in 926 bytes} [Tue Mar 10 14:26:26 2020] GET / => generated 9451 bytes in 939 msecs (HTTP/1.1 401) 7 headers in 360 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
invalid request block size: 21573 (max 4096)...skip
[pid: 12731|app: 0|req: 1/2] 127.0.0.1 () {46 vars in 926 bytes} [Tue Mar 10 14:27:52 2020] GET / => generated 9451 bytes in 399 msecs (HTTP/1.1 401) 7 headers in 360 bytes (1 switches on core 0)
[pid: 12732|app: 0|req: 1/3] 127.0.0.1 () {48 vars in 974 bytes} [Tue Mar 10 14:27:55 2020] GET / => generated 11758 bytes in 963 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 12734|app: 0|req: 1/4] 127.0.0.1 () {48 vars in 953 bytes} [Tue Mar 10 14:27:56 2020] GET /favicon.ico => generated 13173 bytes in 372 msecs (HTTP/1.1 404) 3 headers in 103 bytes (1 switches on core 0)
[pid: 12732|app: 0|req: 2/5] 127.0.0.1 () {50 vars in 1040 bytes} [Tue Mar 10 14:27:59 2020] GET /categoryitems/ => generated 11935 bytes in 325 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
invalid request block size: 21573 (max 4096)...skip
[pid: 12731|app: 0|req: 2/6] 127.0.0.1 () {44 vars in 750 bytes} [Tue Mar 10 14:33:16 2020] GET /category/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 2/7] 127.0.0.1 () {44 vars in 781 bytes} [Tue Mar 10 14:35:44 2020] GET /articleList/?ordering=-id => generated 43 bytes in 4 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 3/8] 127.0.0.1 () {44 vars in 750 bytes} [Tue Mar 10 14:35:44 2020] GET /category/ => generated 43 bytes in 2 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 4/9] 127.0.0.1 () {44 vars in 764 bytes} [Tue Mar 10 14:35:44 2020] GET /hot_articleList/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 5/10] 127.0.0.1 () {44 vars in 738 bytes} [Tue Mar 10 14:35:44 2020] GET /ad/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12732|app: 0|req: 3/11] 127.0.0.1 () {42 vars in 595 bytes} [Tue Mar 10 14:47:08 2020] POST /category/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 6/12] 127.0.0.1 () {42 vars in 595 bytes} [Tue Mar 10 14:47:37 2020] POST /category/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 7/13] 127.0.0.1 () {42 vars in 595 bytes} [Tue Mar 10 14:48:09 2020] POST /category/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 8/14] 127.0.0.1 () {44 vars in 781 bytes} [Tue Mar 10 14:56:18 2020] GET /articleList/?ordering=-id => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 9/15] 192.168.1.188 () {44 vars in 758 bytes} [Tue Mar 10 14:56:18 2020] GET /category/ => generated 43 bytes in 2 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 10/16] 127.0.0.1 () {44 vars in 764 bytes} [Tue Mar 10 14:56:18 2020] GET /hot_articleList/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12734|app: 0|req: 11/17] 127.0.0.1 () {44 vars in 738 bytes} [Tue Mar 10 14:56:18 2020] GET /ad/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12733|app: 0|req: 2/18] 127.0.0.1 () {44 vars in 781 bytes} [Tue Mar 10 14:58:31 2020] GET /articleList/?ordering=-id => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12733|app: 0|req: 3/19] 127.0.0.1 () {44 vars in 750 bytes} [Tue Mar 10 14:58:31 2020] GET /category/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
[pid: 12732|app: 0|req: 4/20] 127.0.0.1 () {44 vars in 764 bytes} [Tue Mar 10 14:58:31 2020] GET /hot_articleList/ => generated 43 bytes in 2 msecs (HTTP/1.1 401) 6 headers in 188 bytes (1 switches on core 0)
[pid: 12733|app: 0|req: 4/21] 127.0.0.1 () {44 vars in 738 bytes} [Tue Mar 10 14:58:31 2020] GET /ad/ => generated 43 bytes in 1 msecs (HTTP/1.1 401) 6 headers in 194 bytes (1 switches on core 0)
Tue Mar 10 16:06:36 2020 - *** /home/hadoop0/Django_P/Django_API/newsapi has been touched... grace them all !!! ***
...gracefully killing workers...
Gracefully killing worker 1 (pid: 12731)...
Gracefully killing worker 3 (pid: 12733)...
Gracefully killing worker 2 (pid: 12732)...
Gracefully killing worker 4 (pid: 12734)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 16:06:37 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x9a6f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x9a6f90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 14458, cores: 1)
spawned uWSGI worker 2 (pid: 14459, cores: 1)
spawned uWSGI worker 3 (pid: 14460, cores: 1)
spawned uWSGI worker 4 (pid: 14461, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Not Found: /
[pid: 14459|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 1005 bytes} [Tue Mar 10 17:34:49 2020] GET / => generated 2257 bytes in 354 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /category
[pid: 14460|app: 0|req: 1/2] 127.0.0.1 () {48 vars in 990 bytes} [Tue Mar 10 17:35:03 2020] GET /category => generated 2299 bytes in 323 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 14458|app: 0|req: 1/3] 127.0.0.1 () {50 vars in 1021 bytes} [Tue Mar 10 17:35:23 2020] GET /category => generated 0 bytes in 338 msecs (HTTP/1.1 301) 3 headers in 115 bytes (1 switches on core 0)
Not Found: /category/
[pid: 14460|app: 0|req: 2/4] 127.0.0.1 () {50 vars in 1023 bytes} [Tue Mar 10 17:35:24 2020] GET /category/ => generated 2302 bytes in 7 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /category/
[pid: 14460|app: 0|req: 3/5] 127.0.0.1 () {50 vars in 1023 bytes} [Tue Mar 10 17:35:26 2020] GET /category/ => generated 2302 bytes in 9 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 14461|app: 0|req: 1/6] 127.0.0.1 () {48 vars in 974 bytes} [Tue Mar 10 17:35:29 2020] GET / => generated 11758 bytes in 593 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
Not Found: /category/
[pid: 14460|app: 0|req: 4/7] 127.0.0.1 () {50 vars in 1030 bytes} [Tue Mar 10 17:35:36 2020] GET /category/ => generated 2302 bytes in 7 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /category/
[pid: 14460|app: 0|req: 5/8] 127.0.0.1 () {52 vars in 1061 bytes} [Tue Mar 10 17:35:40 2020] GET /category/ => generated 2302 bytes in 8 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /tag/
[pid: 14460|app: 0|req: 6/9] 127.0.0.1 () {50 vars in 1020 bytes} [Tue Mar 10 17:36:08 2020] GET /tag/ => generated 2287 bytes in 10 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 14459)...
Gracefully killing worker 1 (pid: 14458)...
Gracefully killing worker 3 (pid: 14460)...
Gracefully killing worker 4 (pid: 14461)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 17:37:00 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x10a9f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x10a9f90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 15267, cores: 1)
spawned uWSGI worker 2 (pid: 15268, cores: 1)
spawned uWSGI worker 3 (pid: 15269, cores: 1)
spawned uWSGI worker 4 (pid: 15270, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 15270|app: 0|req: 1/1] 127.0.0.1 () {52 vars in 1051 bytes} [Tue Mar 10 17:37:24 2020] GET /tag/ => generated 14298 bytes in 703 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
[pid: 15270|app: 0|req: 2/2] 127.0.0.1 () {48 vars in 974 bytes} [Tue Mar 10 17:37:30 2020] GET / => generated 11758 bytes in 173 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 15270|app: 0|req: 3/3] 127.0.0.1 () {50 vars in 1030 bytes} [Tue Mar 10 17:37:32 2020] GET /category/ => generated 14659 bytes in 186 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
[pid: 15270|app: 0|req: 4/4] 127.0.0.1 () {50 vars in 1036 bytes} [Tue Mar 10 17:37:46 2020] GET /articleList/ => generated 22691 bytes in 644 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 15267)...
Gracefully killing worker 4 (pid: 15270)...
Gracefully killing worker 2 (pid: 15268)...
Gracefully killing worker 3 (pid: 15269)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 17:43:32 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xf61f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xf61f90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 15416, cores: 1)
spawned uWSGI worker 2 (pid: 15417, cores: 1)
spawned uWSGI worker 3 (pid: 15418, cores: 1)
spawned uWSGI worker 4 (pid: 15419, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 15419|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 1005 bytes} [Tue Mar 10 17:43:43 2020] GET / => generated 11758 bytes in 619 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 15419|app: 0|req: 2/2] 127.0.0.1 () {50 vars in 1005 bytes} [Tue Mar 10 17:43:50 2020] GET / => generated 11758 bytes in 169 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
[pid: 15419|app: 0|req: 3/3] 127.0.0.1 () {50 vars in 1030 bytes} [Tue Mar 10 17:43:53 2020] GET /category/ => generated 12901 bytes in 183 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 15416)...
Gracefully killing worker 2 (pid: 15417)...
Gracefully killing worker 3 (pid: 15418)...
Gracefully killing worker 4 (pid: 15419)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 17:44:35 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xef5f90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xef5f90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 15465, cores: 1)
spawned uWSGI worker 2 (pid: 15466, cores: 1)
spawned uWSGI worker 3 (pid: 15467, cores: 1)
spawned uWSGI worker 4 (pid: 15468, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 15466|app: 0|req: 1/1] 127.0.0.1 () {52 vars in 1061 bytes} [Tue Mar 10 17:44:43 2020] GET /category/ => generated 12901 bytes in 635 msecs (HTTP/1.1 200) 6 headers in 320 bytes (1 switches on core 0)
[pid: 15466|app: 0|req: 2/2] 127.0.0.1 () {48 vars in 974 bytes} [Tue Mar 10 17:44:49 2020] GET / => generated 11758 bytes in 173 msecs (HTTP/1.1 200) 6 headers in 314 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 2 (pid: 15466)...
Gracefully killing worker 1 (pid: 15465)...
Gracefully killing worker 3 (pid: 15467)...
Gracefully killing worker 4 (pid: 15468)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 17:45:58 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0xe1cf90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xe1cf90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 15532, cores: 1)
spawned uWSGI worker 2 (pid: 15533, cores: 1)
spawned uWSGI worker 3 (pid: 15534, cores: 1)
spawned uWSGI worker 4 (pid: 15535, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
[pid: 15535|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 1005 bytes} [Tue Mar 10 17:46:11 2020] GET / => generated 699 bytes in 552 msecs (HTTP/1.1 200) 4 headers in 128 bytes (1 switches on core 0)
[pid: 15535|app: 0|req: 2/2] 127.0.0.1 () {48 vars in 992 bytes} [Tue Mar 10 17:46:25 2020] GET /category/ => generated 129 bytes in 144 msecs (HTTP/1.1 200) 4 headers in 134 bytes (1 switches on core 0)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 15532)...
Gracefully killing worker 2 (pid: 15533)...
Gracefully killing worker 3 (pid: 15534)...
Gracefully killing worker 4 (pid: 15535)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (127.0.0.1:8005)
running /home/hadoop0/anaconda3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Tue Mar 10 17:46:52 2020] ***
compiled with version: 5.4.0 20160609 on 03 December 2019 11:37:40
os: Linux-4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020
nodename: spark
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /home/hadoop0/Django_P/Django_API/newsapi
detected binary path: /home/hadoop0/anaconda3/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/hadoop0/Django_P/Django_API/newsapi
your processes number limit is 22854
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited INET address 127.0.0.1:8005 fd 3
Python version: 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06)  [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x10dcf90
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 364520 bytes (355 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x10dcf90 pid: 12721 (default app)
mountpoint  already configured. skip.
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 12721)
spawned uWSGI worker 1 (pid: 15583, cores: 1)
spawned uWSGI worker 2 (pid: 15584, cores: 1)
spawned uWSGI worker 3 (pid: 15585, cores: 1)
spawned uWSGI worker 4 (pid: 15586, cores: 1)
*** Stats server enabled on 127.0.0.1:9095 fd: 16 ***
Not Found: /category/
[pid: 15584|app: 0|req: 1/1] 127.0.0.1 () {50 vars in 1023 bytes} [Tue Mar 10 17:47:00 2020] GET /category/ => generated 2302 bytes in 342 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /category/
[pid: 15583|app: 0|req: 1/2] 127.0.0.1 () {50 vars in 1023 bytes} [Tue Mar 10 17:47:04 2020] GET /category/ => generated 2302 bytes in 348 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
